### ISSUE TITLE
Xcode 11 beta 打不开 Canvas 页面有遇到吗？

### ISSUE THREAD

**Issue by mazingyu** [Jinxiansen/SwiftUI#1]
如题。

**Comment by weichengwu** [comment]
[官方教程](https://developer.apple.com/tutorials/swiftui/creating-and-combining-views)一开始就说了：“请确保你的 macOS 版本在 10.15 beta 以上”
![image](https://user-images.githubusercontent.com/17878528/58858711-bfc71a80-86da-11e9-8b4e-4c4276ee1f89.png)

**Comment by weichengwu** [comment]
要确保 macOS 版本已升级到 10.15 beta
![image](https://user-images.githubusercontent.com/17878528/58858950-4ed43280-86db-11e9-8b23-d7d5851a4515.png)

**Comment by Jinxiansen** [comment]
是的，👍
需要 macOS 10.15 beta 。

**Comment by SilkSong** [comment]
还有另一种方法：使用 Playground, 具体参见https://twitter.com/johnsundell/status/1139190006227120128
