### ISSUE TITLE
viewDidLoad equivalent?

### ISSUE THREAD

**Issue by Reak45** [Jinxiansen/SwiftUI#10]
Hi,
Currently I am looking into TabbedView and I have a question. I was managed to create a simple app containing two tabs and now I am trying to load the data **once** after the tab was loaded. I tried using **onAppear** method but unfortunately it is called every time a tab was selected. Any ideas how to handle such logic?

**Comment by TrustTheBoy** [comment]
same

**Comment by Jinxiansen** [comment]
Maybe you can put the data on the outside or use a singleton.
