### ISSUE TITLE
Hi - Not Compiling on Xcode Version 11.0 beta 4 (11M374r)

### ISSUE THREAD

**Issue by waelsaad** [Jinxiansen/SwiftUI#11]
I think these are great examples to learn from, would you please fix the compilation issues for Xcode Version 11.0 beta 4 (11M374r)?

Thank you,

Wael

**Comment by wanliming11** [comment]
Same in  beta 5.

**Comment by Jinxiansen** [comment]
I will update after the official release, as there are many changes from beta 1-7.
😅
