### ISSUE TITLE
很多过期的内容

### ISSUE THREAD

**Issue by yanglfree** [Jinxiansen/SwiftUI#15]
## Version
macOS version: 10.15Beta

Xcode version:  11.0 Beta 6
 
## Description

Describe your problem:
很多View已经被移除或者用法改变了
内容没有及时更新

**Comment by SpectatorNan** [comment]
具体表现？或说明某个文件，我这使用最新xcode正式版 运行无问题

**Comment by Jinxiansen** [comment]
@yanglfree  Beta 版的 API 变动较大，请更新至 Xcode 11.0 正式版 。
