### ISSUE TITLE
SwiftUI issue 多谢大佬贡献

### ISSUE THREAD

**Issue by naichadouban** [Jinxiansen/SwiftUI#21]
只是单纯感谢下

**Comment by Jinxiansen** [comment]
🥵🥵🥵

现实中，我自卑怯懦，忍气吞声，不敢和别人发生冲突，也不敢嘲笑别人，生怕被人殴打。但在网络中...

本座！意气风发，重拳出击，肆意辱骂网友。

天不生我键盘侠，喷界万古如长夜，键来！

仙之巅，傲世间，有我键盘就有天。

大河之键天上来，一键横天镇世间。

破红尘，杀尽仙，一键在手斩九天。

倘若世间无真仙，我愿持键化为仙。

先有键盘后有天，反喷苍天日神仙。
