### ISSUE TITLE
SwiftUI issue

### ISSUE THREAD

**Issue by Jamxscape** [Jinxiansen/SwiftUI#25]
## Version
macOS version:
10.15.4
Xcode version: 
11.4.1
## Description
初学者，TextField那儿按照楼主的方法全都报错了，后来我找到了这个是正确的的
`TextField("User Name", text: $username, onEditingChanged: { (value) in
                    print("onEditingChanged:\(self.name)")
                }) {
                    print("onCommit:\(self.name)")
                }}
                .padding(10)
                .frame(height: 50)
                .textFieldStyle(RoundedBorderTextFieldStyle())
                .padding(EdgeInsets(top: 0, leading: 20, bottom: 0, trailing: 20))`
Describe your problem:

**Comment by Jinxiansen** [comment]
可能部分 API 在不同 Xcode 上已经变更或废弃了，我这里用的还是 Xcode 11.2.1 运行无碍。
