### ISSUE TITLE
Popover drag to dismiss seems buggy

### ISSUE THREAD

**Issue by Petr-2019** [Jinxiansen/SwiftUI#26]
## Version
macOS version:
10.15.4

Xcode version: 
11.5

iOS version:
13.5.1

## Description
Popover drag to dismiss seems buggy

Describe your problem:

Check the gif:
![Jun-05-2020 11-26-24](https://user-images.githubusercontent.com/7663073/83833829-719a8c00-a71f-11ea-9b0d-741df7ed2492.gif)

**Comment by Jinxiansen** [comment]
Yes, this is just a usage example.
