### ISSUE TITLE
Big sur  not working

### ISSUE THREAD

**Issue by huangboju** [Jinxiansen/SwiftUI#29]
## Version
macOS version:
Big sur 11.0.1

Xcode version: 
12.2

## Description

Describe your problem:
这下面的Demo跑不起来了
https://github.com/Jinxiansen/SwiftUI/tree/doc

**Comment by Jinxiansen** [comment]
最近在北京出差，恐无时间看这个问题，如果你有兴趣的话可以找出原因所在提个PR，感谢！
