### ISSUE TITLE
Picker example

### ISSUE THREAD

**Issue by muhammadelkady25** [Jinxiansen/SwiftUI#5]
Could you provide a picker example containing for example list of chars [A..Z] or lis of numbers [0..9]

**Comment by Jinxiansen** [comment]
@muhammadelkady25

**Comment by Jinxiansen** [comment]
![Picker](https://user-images.githubusercontent.com/16829428/59291724-1077de00-8cae-11e9-890b-d4750ee24a96.png)


I have added the `Picker` usage example, as shown above.
You can download the project to view the source code.
https://github.com/Jinxiansen/SwiftUI#Picker

**Comment by muhammadelkady25** [comment]
Thank you very much for your help

**Comment by Jinxiansen** [comment]
≖‿≖

**Comment by muhammadelkady25** [comment]
@Jinxiansen another thing .. in the example the second picker overlaps the first one .. the area in the middle (2 gray lines overlaps each other) .. I have six pickers. The last one receives touch in the overlapped area. how to give it a fixed width ?

```
 Picker(selection: $firstLetterIndex, label: Text("")) {
                    ForEach(0..<letters.count) {
                        Text(self.letters[$0]).tag($0)
                    }
                }.fixedSize().frame(width: 20)

```
This did not work for me

**Comment by Jinxiansen** [comment]
<img width="268" alt="Jietu20190612-223205@2x" src="https://user-images.githubusercontent.com/16829428/59359995-f697d300-8d61-11e9-916b-7101aaa9484c.png">

I tried to arrange 6 Pickers horizontally, which caused the top 5 Texts to not display properly, and when the first Picker swung up and down, it responded with the value of the third Picker. Maybe this is a bug in SwiftUI.😂
