### ISSUE TITLE
How about a Q&A?

### ISSUE THREAD

**Issue by likeSo** [Jinxiansen/SwiftUI#6]
感谢分享! 现在我们已经知道了如何使用各个UI组件, 那么下一步, 如何使用SwiftUI来实现更深层次的UI功能定制?
比如:
- 如何使TextField失去焦点?
- 如何定制TextField的键盘样式?
- 如何指定TextField的contentType?
- 如何为每个页面指定键盘(textInputContextIdentifier)?
还有其他等等更多, 能否整合一个Q&A页面, 请大家解答各种这样的问题?

Now we know how to compose view controllers by SwiftUI. But then? 
- How to 'resign first responder' for a TextField manually?
- How to customize keyboard type of TextField?
- How to provide contentType of TextField?
- How to provide textInputContextIdentifier for views?
And more...

**Comment by Jinxiansen** [comment]
你的建议非常有用！💪
非常感谢！
但由于工作和业余时间的事情较多，我尝试抽点时间来完善这方面。
如果有兴趣，也欢迎一起来完善！

**Comment by likeSo** [comment]
谢谢, 不一定要你自己维护的, 现在SwiftUI刚刚发布没多久, 大家都是没有实际项目经验的同学🤣🤣现在已有一千多人点赞了这个repo, 你提供一个版面, 相信会有人愿意一起参与进来共享知识的😊

**Comment by Jinxiansen** [comment]
👍👍👍  谢谢你的好建议！
