### ISSUE TITLE
'String' is not convertible to 'String?'

### ISSUE THREAD

**Issue by iosApem** [Jinxiansen/SwiftUI#7]
xcode Version 11.0 beta 2 (11M337n)
模拟器：iphone xr ios 13

运行
PageRow(title: "WebView",subTitle: "用于展示一个打开的网页")
报错内容：'String' is not convertible to 'String?'

我不懂swift的语法，不知道该怎么解决

**Comment by Jinxiansen** [comment]
可以贴出更多的代码嘛，这应该是一个 可选类型的提示，你可以了解一下 Swift 的 Optional Chaining：https://www.runoob.com/swift/swift-optional-chaining.html

**Comment by likeSo** [comment]
你这个问题我遇到过，这个报错的意思与真正的错误毫无关系...你应该检查在这段代码前面是否有其他的语法错误，这个报错感觉就是新Xcode的bug...

**Comment by iosApem** [comment]
建议大佬用最新的xcode编译一下，不止这个报错。：）

**Comment by likeSo** [comment]
> 建议大佬用最新的xcode编译一下，不止这个报错。：）

你考虑一下我说的，这个报错不代表真正的报错，所以有其他的报错很正常啊，你把其他的报错改掉了，这个问题也就不存在了

**Comment by Jinxiansen** [comment]
😅😅 ·

**Comment by wang-yapu** [comment]
> > 建议大佬用最新的xcode编译一下，不止这个报错。：）
> 
> 你考虑一下我说的，这个报错不代表真正的报错，所以有其他的报错很正常啊，你把其他的报错改掉了，这个问题也就不存在了

问题是其他都改掉了,这个问题也还存在
![8E0BE7EF-2DDD-4438-80DA-7C94B8890C2B](https://user-images.githubusercontent.com/12498935/60392303-9a3efc80-9b32-11e9-816b-e8967936a72d.png)

**Comment by likeSo** [comment]
@iosApem 我用beta2跑了一下Example确实有这个问题，不排除是beta2的bug，我看了一下Beta2的[Release Note](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_2_release_notes)里面确实有一些关于SwiftUI的诡异的已知问题，建议手敲一遍吧，或者尝试使用Beta1 :)

**Comment by Jinxiansen** [comment]
😂
@likeSo @iosApem @wang-yapu 
在下在 Xcode  尝试了下，确实报错如上，但是报的错并非是 String 的问题，而是 `PresentationButton` 这个方法在 Beta2 参数有变动导致。
我在这个分支修复了此问题：https://github.com/Jinxiansen/SwiftUI/tree/Xcode_Beta2(11M337n)

**Comment by bajiejiedian** [comment]
> 😂
> @likeSo @iosApem @wang-yapu
> 在下在 Xcode( Version 11.0 beta 2 (11M337n) ) 尝试了下，确实报错如上，但是报的错并非是 String 的问题，而是 `PresentationButton` 这个方法在 Beta2 参数有变动导致。
> 我在这个分支修复了此问题：https://github.com/Jinxiansen/SwiftUI/tree/Xcode_Beta2(11M337n)

Xcode Version 11.0 beta 3 (11M362v)还是报这个错误😂

**Comment by Jinxiansen** [comment]
Beta 版本极其不稳定，每次更新都会废弃几个类导致。😌

**Comment by legolasW** [comment]
TextField 在 Beta 4 中语法变更，Developer Document 暂时没更新。
新写法：public init(_ titleKey: LocalizedStringKey, text: Binding<String>, onEditingChanged: @escaping (Bool) -> Void

**Comment by Jinxiansen** [comment]
👍 好的，感谢！
